### ISSUE TITLE
Unable to Edit Large tEXt Chunks

### ISSUE THREAD

**Issue by ian-cassias** [jsummers/tweakpng#9]
The Edit Chunk text editor is unable to edit tEXt chunks with length > 30,000 characters, which is the default limit for the edit control. This limit can be increased by adding the following line of code to Dlg_tEXt_InitDialog in chunk.cpp:

`SendDlgItemMessage(hwnd, IDC_TEXTTEXT, EM_SETLIMITTEXT, 0, 0);`

Reference:
[https://docs.microsoft.com/en-us/windows/win32/controls/em-setlimittext](https://docs.microsoft.com/en-us/windows/win32/controls/em-setlimittext)
[https://stackoverflow.com/questions/180853/cedit-control-maximum-length-in-characters-it-can-display](https://stackoverflow.com/questions/180853/cedit-control-maximum-length-in-characters-it-can-display)

**Comment by tns-icassias** [comment]
Thank you!
